export const CHANGE_TICKETS = 'CHANGE_TICKETS';
export const CHANGE_COURSES = 'CHANGE_COURSES';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const CHANGE_STOPS = 'CHANGE_STOPS';
export const CHANGE_ONLY_STOPS = 'CHANGE_ONLY_STOPS';